include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'

stages:
  - pre-package
  - package
  - post-package

.docker-build:
  variables:
    COMPOSE_FILE_NAME: docker-compose.yml
